<?php
namespace gamboamartin\comercial\models;
use base\orm\modelo;
use gamboamartin\direccion_postal\models\dp_calle_pertenece;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class com_sucursal extends modelo{

    public function __construct(PDO $link){
        $tabla = 'com_sucursal';
        $columnas = array($tabla=>false,'com_cliente'=>$tabla,'dp_calle_pertenece'=>$tabla,
            'dp_colonia_postal'=>'dp_calle_pertenece','dp_cp'=>'dp_colonia_postal',
            'cat_sat_regimen_fiscal'=>'com_cliente');
        $campos_obligatorios = array('descripcion','codigo','descripcion_select','alias','codigo_bis',
            'numero_exterior','com_cliente_id','dp_calle_pertenece_id');

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);

        $this->NAMESPACE =__NAMESPACE__;

    }

    public function alta_bd(): array|stdClass
    {

        $keys = array('com_cliente_id','dp_calle_pertenece_id');
        $valida = $this->validacion->valida_ids(keys:$keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $com_cliente = (new com_cliente($this->link))->registro(registro_id: $this->registro['com_cliente_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener com_cliente',data:  $com_cliente);
        }

        $dp_calle_pertenece = (new dp_calle_pertenece($this->link))->registro(
            registro_id: $this->registro['dp_calle_pertenece_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener dp_calle_pertenece',data:  $com_cliente);
        }

        if(!isset($this->registro['descripcion_select'])){
            $descripcion_select = $com_cliente['com_cliente_rfc'].' '.$com_cliente['com_cliente_razon_social'].' '.
                $dp_calle_pertenece['dp_municipio_descripcion'];

            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if(!isset($this->registro['alias'])){
            $alias = strtoupper($this->registro['descripcion_select']);

            $this->registro['alias'] = $alias;
        }

        if(!isset($this->registro['codigo_bis'])){
            $codigo_bis = strtoupper($this->registro['codigo']);

            $this->registro['codigo_bis'] = $codigo_bis;
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar com_sucursal',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }
}