<?php
namespace gamboamartin\comercial\models;
use base\orm\_modelo_parent;
use gamboamartin\administrador\models\adm_usuario;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class com_agente extends _modelo_parent{
    public function __construct(PDO $link, array $childrens = array()){
        $tabla = 'com_agente';
        $columnas = array($tabla=>false,'com_tipo_agente'=>$tabla,'adm_usuario'=>$tabla);
        $campos_obligatorios = array('adm_usuario_id','com_tipo_agente_id');
        $childrens['com_prospecto'] ="gamboamartin\comercial\models";

        $columnas_extra['com_agente_n_prospectos'] =
            "(SELECT COUNT(*) FROM com_prospecto WHERE com_prospecto.com_agente_id = com_agente.id)";

        $atributos_criticos[] = 'adm_usuario_id';
        $atributos_criticos[] = 'com_tipo_agente_id';


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, childrens: $childrens,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Agentes';


    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['nombre'];
            $descripcion .= ' '.$this->registro['apellido_paterno'];
            if(!isset($this->registro['apellido_materno'])){
                $this->registro['apellido_materno'] = '';
            }
            $descripcion .= ' '.$this->registro['apellido_materno'];
            $this->registro['descripcion'] = trim($descripcion);
        }

        $adm_usuario_ins['user'] = $this->registro['user'];
        $adm_usuario_ins['password'] = $this->registro['password'];
        $adm_usuario_ins['email'] = $this->registro['email'];
        $adm_usuario_ins['telefono'] = $this->registro['telefono'];
        $adm_usuario_ins['adm_grupo_id'] = $this->registro['adm_grupo_id'];
        $adm_usuario_ins['nombre'] = $this->registro['nombre'];
        $adm_usuario_ins['ap'] = $this->registro['apellido_paterno'];
        $adm_usuario_ins['am'] = $this->registro['apellido_materno'];

        $r_adm_usuario = (new adm_usuario(link: $this->link))->alta_registro(registro: $adm_usuario_ins);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar usuario',data:  $r_adm_usuario);
        }

        $this->registro['adm_usuario_id'] = $r_adm_usuario->registro_id;


        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al r_alta_bd agente',data:  $r_alta_bd);
        }
        return $r_alta_bd;

    }

    public function prospectos(int $com_agente_id): array
    {
        if($com_agente_id <= 0){
            return $this->error->error(mensaje: 'Error com_agente_id debe ser mayor a 0',data:  $com_agente_id);
        }

        $filtro['com_agente.id'] = $com_agente_id;

        $data = (new com_prospecto($this->link))->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener clientes',data:  $data);
        }
        return $data->registros;
    }
}