<?php
namespace gamboamartin\comercial\models;
use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class com_email_cte extends _modelo_parent{

    public function __construct(PDO $link, array $childrens = array()){
        $tabla = 'com_email_cte';
        $columnas = array($tabla=>false,'com_cliente'=>$tabla);
        $campos_obligatorios = array();



        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, childrens: $childrens);

        $this->NAMESPACE = __NAMESPACE__;

        $this->etiqueta = 'Emails';

    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $registro = $this->integra_codigo();
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al al integrar codigo', data: $registro);
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta correo',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }

    /**
     * Genera un codigo aleatorio
     * @param string $descripcion Descripcion de registro
     * @return array|string
     * @version 7.4.1
     */
    private function codigo(string $descripcion): array|string
    {
        $descripcion = trim($descripcion);
        $rand = mt_rand(10000, 99999);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al al integrar rand', data: $rand);
        }
        return trim($descripcion.$rand);
    }

    /**
     * Integra el codigo default
     * @return array
     * 
     */
    private function integra_codigo(): array
    {
        if(!isset($this->registro['codigo'])) {
            $codigo = $this->codigo(descripcion: $this->registro['descripcion']);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al al integrar codigo', data: $codigo);
            }
            $this->registro['codigo'] = $codigo;
        }
        return $this->registro;
    }


}