<?php
namespace gamboamartin\comercial\models;
use base\orm\modelo;
use gamboamartin\cat_sat\models\cat_sat_forma_pago;
use gamboamartin\cat_sat\models\cat_sat_metodo_pago;
use gamboamartin\cat_sat\models\cat_sat_moneda;
use gamboamartin\cat_sat\models\cat_sat_regimen_fiscal;
use gamboamartin\cat_sat\models\cat_sat_tipo_de_comprobante;
use gamboamartin\cat_sat\models\cat_sat_uso_cfdi;
use gamboamartin\direccion_postal\models\dp_calle_pertenece;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class com_cliente extends modelo{
    public function __construct(PDO $link){
        $tabla = 'com_cliente';
        $columnas = array($tabla=>false,'cat_sat_moneda'=>$tabla,'dp_pais'=>'cat_sat_moneda');
        $campos_obligatorios = array('cat_sat_moneda_id','cat_sat_regimen_fiscal_id','cat_sat_moneda_id',
            'cat_sat_forma_pago_id','cat_sat_uso_cfdi_id','cat_sat_tipo_de_comprobante_id','cat_sat_metodo_pago_id');

        $tipo_campos = array();
        $tipo_campos['rfc'] = 'rfc';

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, tipo_campos: $tipo_campos);

        $this->NAMESPACE = __NAMESPACE__;
    }
    public function alta_bd(): array|stdClass
    {

        $registro = $this->descripcion_select(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al asignar descripcion select', data: $registro);
        }

        if(!isset($registro['cat_sat_moneda_id']) || $registro['cat_sat_moneda_id'] === -1){
            $id_predeterminado = (new cat_sat_moneda($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener moneda predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_moneda_id'] = $id_predeterminado;
        }

        if(!isset($registro['dp_calle_pertenece_id']) || $registro['dp_calle_pertenece_id'] === -1){
            $id_predeterminado = (new dp_calle_pertenece($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener dp_calle_pertenece predeterminada', data: $id_predeterminado);
            }
            $registro['dp_calle_pertenece_id'] = $id_predeterminado;
        }

        if(!isset($registro['cat_sat_regimen_fiscal_id']) || $registro['cat_sat_regimen_fiscal_id'] === -1){
            $id_predeterminado = (new cat_sat_regimen_fiscal($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cat_sat_regimen_fiscal predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_regimen_fiscal_id'] = $id_predeterminado;
        }

        if(!isset($registro['cat_sat_forma_pago_id']) || $registro['cat_sat_forma_pago_id'] === -1){
            $id_predeterminado = (new cat_sat_forma_pago($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cat_sat_forma_pago_id predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_forma_pago_id'] = $id_predeterminado;
        }

        if(!isset($registro['cat_sat_uso_cfdi_id']) || $registro['cat_sat_uso_cfdi_id'] === -1){
            $id_predeterminado = (new cat_sat_uso_cfdi($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cat_sat_uso_cfdi predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_uso_cfdi_id'] = $id_predeterminado;
        }
        if(!isset($registro['cat_sat_tipo_de_comprobante_id']) || $registro['cat_sat_tipo_de_comprobante_id'] === -1){
            $id_predeterminado = (new cat_sat_tipo_de_comprobante($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cat_sat_tipo_de_comprobante predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_tipo_de_comprobante_id'] = $id_predeterminado;
        }

        if(!isset($registro['cat_sat_metodo_pago_id']) || $registro['cat_sat_metodo_pago_id'] === -1){
            $id_predeterminado = (new cat_sat_metodo_pago($this->link))->id_predeterminado();
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener cat_sat_metodo_pago predeterminada', data: $id_predeterminado);
            }
            $registro['cat_sat_metodo_pago_id'] = $id_predeterminado;
        }



        $this->registro = $registro;

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta registro', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    /**
     * Ajusta la descripcion select
     * @param array $registro Registro en proceso de alta
     * @return array
     * @version 0.28.6
     */
    private function descripcion_select(array $registro): array
    {
        $keys = array('codigo','razon_social','rfc');
        $valida = $this->validacion->valida_existencia_keys(keys:$keys, registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro', data: $valida);
        }
        if(!isset($registro['descripcion_select']) || $registro['descripcion_select'] === ''){
            $registro['descripcion_select'] = $registro['codigo'];
            $registro['descripcion_select'] .= ' '.$registro['rfc'];
            $registro['descripcion_select'] .= ' '.$registro['razon_social'];
        }
        return $registro;
    }
}