<?php
namespace gamboamartin\comercial\models;
use base\orm\modelo;
use gamboamartin\direccion_postal\models\dp_calle_pertenece;
use gamboamartin\direccion_postal\models\dp_pais;
use gamboamartin\direccion_postal\models\dp_colonia;
use gamboamartin\direccion_postal\models\dp_cp;
use gamboamartin\direccion_postal\models\dp_municipio;
use gamboamartin\direccion_postal\models\dp_estado;

use gamboamartin\errores\errores;
use PDO;
use stdClass;

class com_sucursal extends modelo{

    public function __construct(PDO $link){
        $tabla = 'com_sucursal';
        $columnas = array($tabla=>false,'com_cliente'=>$tabla,'dp_calle_pertenece'=>$tabla,
            'dp_colonia_postal'=>'dp_calle_pertenece','dp_cp'=>'dp_colonia_postal',
            'cat_sat_regimen_fiscal'=>'com_cliente','dp_municipio'=>'dp_cp');
        $campos_obligatorios = array('descripcion','codigo','descripcion_select','alias','codigo_bis',
            'numero_exterior','com_cliente_id', 'dp_calle_pertenece_id');

        $tipo_campos = array();

        $campos_view = array();
        $campos_view['dp_colonia_id']['type'] = 'selects';
        $campos_view['dp_colonia_id']['model'] = (new dp_colonia($link));

        $campos_view['dp_cp_id']['type'] = 'selects';
        $campos_view['dp_cp_id']['model'] = (new dp_cp($link));

        $campos_view['dp_municipio_id']['type'] = 'selects';
        $campos_view['dp_municipio_id']['model'] = (new dp_municipio($link));

        $campos_view['dp_pais_id']['type'] = 'selects';
        $campos_view['dp_pais_id']['model'] = (new dp_pais($link));

        $campos_view['dp_calle_pertenece_id']['type'] = 'selects';
        $campos_view['dp_calle_pertenece_id']['model'] = (new dp_calle_pertenece($link));

        $campos_view['dp_estado_id']['type'] = 'selects';
        $campos_view['dp_estado_id']['model'] = (new dp_estado($link));

        $campos_view['com_cliente_id']['type'] = 'selects';
        $campos_view['com_cliente_id']['model'] = (new com_cliente($link));

        $campos_view['telefono_3']['type'] = 'inputs';
        $campos_view['telefono_2']['type'] = 'inputs';
        $campos_view['telefono_1']['type'] = 'inputs';
        $campos_view['numero_exterior']['type'] = 'inputs';
        $campos_view['numero_interior']['type'] = 'inputs';
        $campos_view['nombre_contacto']['type'] = 'inputs';

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, tipo_campos: $tipo_campos, campos_view: $campos_view);

        $this->NAMESPACE =__NAMESPACE__;

    }

    public function alta_bd(): array|stdClass
    {

        $keys = array('com_cliente_id','dp_calle_pertenece_id');
        $valida = $this->validacion->valida_ids(keys:$keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $com_cliente = (new com_cliente($this->link))->registro(registro_id: $this->registro['com_cliente_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener com_cliente',data:  $com_cliente);
        }

        $dp_calle_pertenece = (new dp_calle_pertenece($this->link))->registro(
            registro_id: $this->registro['dp_calle_pertenece_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener dp_calle_pertenece',data:  $com_cliente);
        }

        if(!isset($this->registro['descripcion_select'])){
            $descripcion_select = $com_cliente['com_cliente_rfc'].' '.$com_cliente['com_cliente_razon_social'].' '.
                $dp_calle_pertenece['dp_municipio_descripcion'];

            $this->registro['descripcion_select'] = $descripcion_select;
        }

        if(!isset($this->registro['alias'])){
            $alias = strtoupper($this->registro['descripcion_select']);

            $this->registro['alias'] = $alias;
        }

        if(!isset($this->registro['codigo_bis'])){
            $codigo_bis = strtoupper($this->registro['codigo']);

            $this->registro['codigo_bis'] = $codigo_bis;
        }

        if(isset($this->registro['dp_pais_id'])){
            unset($this->registro['dp_pais_id']);
        }
        if(isset($this->registro['dp_estado_id'])){
            unset($this->registro['dp_estado_id']);
        }
        if(isset($this->registro['dp_cp_id'])){
            unset($this->registro['dp_cp_id']);
        }
        if(isset($this->registro['dp_colonia_id'])){
            unset($this->registro['dp_colonia_id']);
        }

        $r_alta_bd = parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar com_sucursal',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false): array|stdClass
    {

        if(isset($registro['dp_pais_id'])){
            unset($registro['dp_pais_id']);
        }
        if(isset($registro['dp_estado_id'])){
            unset($registro['dp_estado_id']);
        }
        if(isset($registro['dp_cp_id'])){
            unset($registro['dp_cp_id']);
        }
        if(isset($registro['dp_colonia_id'])){
            unset($registro['dp_colonia_id']);
        }


        $r_modifica_bd = parent::modifica_bd($registro, $id, $reactiva); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar com_sucursal',data:  $r_modifica_bd);
        }
        return $r_modifica_bd;
    }

    public function sucursales(int $com_cliente_id): array|stdClass
    {
        if($com_cliente_id <=0){
            return $this->error->error(mensaje: 'Error $com_cliente_id debe ser mayor a 0', data: $com_cliente_id);
        }
        $filtro['com_cliente.id'] = $com_cliente_id;
        $r_com_sucursal = $this->filtro_and(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener sucursales', data: $r_com_sucursal);
        }
        return $r_com_sucursal;
    }
}