<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\comercial\controllers;

use base\orm\modelo;
use config\generales;
use gamboamartin\administrador\models\adm_campo;
use gamboamartin\administrador\models\adm_seccion;
use gamboamartin\cat_sat\models\cat_sat_obj_imp;
use gamboamartin\cat_sat\models\cat_sat_producto;
use gamboamartin\cat_sat\models\cat_sat_unidad;
use gamboamartin\comercial\models\_exporta;
use gamboamartin\comercial\models\com_producto;
use gamboamartin\comercial\models\com_tipo_producto;
use gamboamartin\documento\models\doc_documento;
use gamboamartin\errores\errores;
use gamboamartin\plugins\exportador;
use gamboamartin\system\links_menu;
use gamboamartin\template\html;
use html\com_producto_html;
use html\com_tmp_prod_cs_html;
use PDO;
use stdClass;

class controlador_com_producto extends _base_comercial {

    public array|stdClass $keys_selects = array();
    public string $link_com_producto_alta_bd = '';
    public string $link_com_producto_modifica_bd = '';

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new com_producto(link: $link);
        $html = new com_producto_html(html: $html);
        $obj_link = new links_menu(link: $link,registro_id: $this->registro_id);

        $datatables = $this->init_datatable();
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al inicializar datatable',data: $datatables);
            print_r($error);
            die('Error');
        }

        parent::__construct(html:$html, link: $link,modelo:  $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $this->titulo_lista = 'Productos';

        $propiedades = $this->inicializa_propiedades();
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al inicializar propiedades',data:  $propiedades);
            print_r($error);
            die('Error');
        }

        $this->parents_verifica[] = (new cat_sat_producto(link: $this->link));
        $this->parents_verifica[] = (new cat_sat_unidad(link: $this->link));
        $this->parents_verifica[] = (new cat_sat_obj_imp(link: $this->link));
        $this->parents_verifica[] = (new com_tipo_producto(link: $this->link));

        $this->verifica_parents_alta = true;

        $this->modelo_doc_documento = new doc_documento(link: $link);

        $this->doc_tipo_documento_id = 12;
    }


    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta(header: $header,ws:  $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener template',data:  $r_alta, header: $header,ws:  $ws);
        }

        $cat_sat_producto = (new com_tmp_prod_cs_html(html: $this->html_base))->input_cat_sat_producto(
            cols: 6, row_upd: $this->row_upd, value_vacio: false, disabled: false);

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener input',data:  $cat_sat_producto, header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_producto = $cat_sat_producto;

        $link_com_com_producto_alta_bd = $this->obj_link->link_alta_bd(link: $this->link,seccion: $this->seccion);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener link',data:  $link_com_com_producto_alta_bd, header: $header,ws:  $ws);
        }
        $this->link_com_producto_alta_bd = $link_com_com_producto_alta_bd;


        return $r_alta;

    }

    final public function aplica_predial(bool $header, bool $ws): array|stdClass
    {
        $en_transaccion = false;
        if($this->link->inTransaction()){
            $en_transaccion = true;
        }

        if(!$en_transaccion){
            $this->link->beginTransaction();
        }

        $upd = $this->row_upd(key: __FUNCTION__);
        if(errores::$error){
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al obtener row upd',data:  $upd, header: $header,ws:  $ws);
        }
        $this->link->commit();

        $_SESSION[$upd->salida][]['mensaje'] = $upd->mensaje.' del id '.$this->registro_id;
        $this->header_out(result: $upd, header: $header,ws:  $ws);

        return $upd;
    }

    public function get_productos(bool $header, bool $ws = true): array|stdClass
    {
        $keys['com_tipo_producto'] = array('id','descripcion','codigo','codigo_bis');

        $salida = $this->get_out(header: $header,keys: $keys, ws: $ws);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar salida',data:  $salida,header: $header,ws: $ws);
        }

        return $salida;
    }

    protected function campos_view(): array
    {
        $keys = new stdClass();
        $keys->inputs = array('codigo','descripcion');
        $keys->selects = array();

        $init_data = array();
        $init_data['cat_sat_cve_prod'] = "gamboamartin\\cat_sat";
        $init_data['com_tipo_producto'] = "gamboamartin\\comercial";
        $init_data['cat_sat_unidad'] = "gamboamartin\\cat_sat";
        $init_data['cat_sat_obj_imp'] = "gamboamartin\\cat_sat";
        $init_data['cat_sat_conf_imps'] = "gamboamartin\\cat_sat";
        $campos_view = $this->campos_view_base(init_data: $init_data,keys:  $keys);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }

        return $campos_view;
    }

    public function es_automatico(bool $header, bool $ws = true): array|stdClass
    {
        $en_transaccion = false;
        if($this->link->inTransaction()){
            $en_transaccion = true;
        }

        if(!$en_transaccion){
            $this->link->beginTransaction();
        }

        $upd = $this->row_upd(key: __FUNCTION__);
        if(errores::$error){
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al obtener row upd',data:  $upd, header: $header,ws:  $ws);
        }
        $this->link->commit();

        $_SESSION[$upd->salida][]['mensaje'] = $upd->mensaje.' del id '.$this->registro_id;
        $this->header_out(result: $upd, header: $header,ws:  $ws);

        return $upd;

    }

    public function descarga_layout(bool $header, bool $ws = true): array|stdClass
    {

        $adm_campos = (new adm_campo(link: $this->link))->campos_by_seccion(adm_seccion_descripcion: $this->tabla);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener adm_campos', data: $adm_campos, header: $header,
                ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
        }

        $foraneas = $this->modelo->get_foraneas();
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener foraneas', data: $foraneas, header: $header,
                ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
        }


        $contador_hojas = 0;

        $campos_hd = array();
        $registros_plantilla = array();

        $letras = $this->modelo->letras;

        $data_hojas = new stdClass();

        foreach ($adm_campos as $adm_campo){

            $data_adm_campo = (new _exporta())->limpia_adm_campo(adm_campo: $adm_campo);
            if(errores::$error){
                return $this->retorno_error(mensaje: 'Error al limpiar adm_campo', data: $data, header: $header,
                    ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
            }
            $adm_campo = $data_adm_campo->adm_campo;
            if($data_adm_campo->continue){
                continue;
            }


            $campos_hd[] = $adm_campo['adm_campo_descripcion'];

            if($adm_campo['adm_campo_es_foranea'] === 'activo'){

                $nombre_tabla_relacion = (new _exporta())->nombre_tabla_relacion(adm_campo: $adm_campo,foraneas:  $foraneas);
                if(errores::$error){
                    return $this->retorno_error(mensaje: 'Error al obtener nombre_tabla_relacion', data: $nombre_tabla_relacion, header: $header,
                        ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
                }

                $campos_hd[] = $nombre_tabla_relacion.'_codigo';
                $campos_hd[] = $nombre_tabla_relacion;

                $vlookup = (new _exporta())->frm_vlookup(campos_hd: $campos_hd,letras:  $letras,nombre_tabla_relacion:  $nombre_tabla_relacion);
                if(errores::$error){
                    return $this->retorno_error(mensaje: 'Error al obtener vlookup', data: $vlookup, header: $header,
                        ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
                }

                $registros_plantilla[0][$nombre_tabla_relacion] = $vlookup;
                $registros_plantilla[0][$nombre_tabla_relacion.'_id'] = "Identificador de entidad, (entero positivo)";


                $registros = (new _exporta())->rows_rel(link: $this->link,nombre_tabla_relacion:  $nombre_tabla_relacion);
                if(errores::$error){
                    return $this->retorno_error(mensaje: 'Error al obtener registros', data: $registros, header: $header,
                        ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
                }


                $data_hojas = (new _exporta())->data_hojas_xls(contador_hojas: $contador_hojas, data_hojas: $data_hojas,
                    keys: array('id','codigo','descripcion'), nombre_tabla_relacion: $nombre_tabla_relacion, registros: $registros);
                if(errores::$error){
                    return $this->retorno_error(mensaje: 'Error al obtener data_hojas', data: $data_hojas, header: $header,
                        ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
                }


                $contador_hojas++;

            }



        }
        $registros_plantilla[0]['descripcion'] = 'Descripcion de '.$this->tabla;
        $registros_plantilla[0]['codigo'] = "Codigo de $this->tabla(Debe ser único)";
        $registros_plantilla[0]['status'] = 'activo';
        $registros_plantilla[0]['alias'] = '=A2';
        $registros_plantilla[0]['descripcion_select'] = '=B2&" "&A2';
        $registros_plantilla[0]['codigo_bis'] = '=B2';


        $data_hojas = (new _exporta())->data_hojas_xls(contador_hojas: $contador_hojas, data_hojas: $data_hojas,
            keys: $campos_hd, nombre_tabla_relacion: $this->tabla, registros: $registros_plantilla
        );

        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener data_hojas', data: $data_hojas, header: $header,
                ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
        }


        $contador_hojas++;

        $name = $this->tabla;

        $path_base = (new generales())->path_base;

        //print_r($data_hojas);exit;

        $xls = (new exportador(num_hojas: $contador_hojas))->genera_xls(header: true,name:  $name,nombre_hojas:  $data_hojas->nombre_hojas,
            keys_hojas:  $data_hojas->keys_hojas,path_base:  $path_base);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al exportar', data: $xls, header: $header,
                ws: $ws, class: __CLASS__, file: __FILE__, function: __FUNCTION__, line: __LINE__);
        }

    }


    public function key_selects_txt(array $keys_selects): array
    {
        $r_alta = $this->init_alta();
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar alta',data:  $r_alta);
        }


        $keys_selects = $this->key_select(cols:6, con_registros: true,filtro:  array(), key: 'com_tipo_producto_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Tipo Producto');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = $this->key_select(cols:6, con_registros: true,filtro:  array(), key: 'cat_sat_unidad_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Unidad');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = $this->key_select(cols:6, con_registros: true,filtro:  array(), key: 'cat_sat_obj_imp_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Objeto del Impuesto');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = $this->key_select(cols:12, con_registros: true,filtro:  array(), key: 'cat_sat_conf_imps_id',
            keys_selects: $keys_selects, id_selected: -1, label: 'Conf de Impuestos');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'codigo',
            keys_selects:$keys_selects, place_holder: 'Cod');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 12,key: 'descripcion',
            keys_selects:$keys_selects, place_holder: 'Producto');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 12,key: 'precio',
            keys_selects:$keys_selects, place_holder: 'Precio');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        return $keys_selects;
    }

    /**
     * @return stdClass
     * @version 4.40.3
     */
    final public function init_datatable(): stdClass
    {
        $columns["com_producto_id"]["titulo"] = "Id";
        $columns["com_producto_codigo"]["titulo"] = "Código";
        $columns["cat_sat_cve_prod_codigo"]["titulo"] = "Código SAT";
        $columns["cat_sat_cve_prod_descripcion"]["titulo"] = "SAT Producto";
        $columns["cat_sat_unidad_descripcion"]["titulo"] = "SAT Unidad";
        $columns["cat_sat_obj_imp_descripcion"]["titulo"] = "SAT ObjetoImp";
        $columns["com_producto_descripcion"]["titulo"] = "Producto";

        $filtro = array("com_producto.id","com_producto.codigo", "com_producto.descripcion",'cat_sat_cve_prod.codigo');

        $datatables = new stdClass();
        $datatables->columns = $columns;
        $datatables->filtro = $filtro;

        return $datatables;
    }

    /**
     * Asigna las propiedades de inputs de productos
     * @return array
     * @version 6.0.0
     */
    private function inicializa_propiedades(): array
    {


        $identificador = "cat_sat_unidad_id";
        $propiedades = array("label" => "SAT - Unidad",  "cols" => 6);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "cat_sat_obj_imp_id";
        $propiedades = array("label" => "Objeto del Impuesto", "cols" => 6);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "com_tipo_producto_id";
        $propiedades = array("label" => "Tipo Producto", "cols" => 6);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "cat_sat_conf_imps_id";
        $propiedades = array("label" => "Conf Impuestos", "cols" => 12);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "codigo";
        $propiedades = array("place_holder" => "Código", "cols" => 6);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "descripcion";
        $propiedades = array("place_holder" => "Producto", "cols" => 12);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        $identificador = "precio";
        $propiedades = array("place_holder" => "Precio", "cols" => 6);
        $pr =$this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializa',data:  $pr);
        }

        return $this->keys_selects;
    }

    public function modifica(bool $header, bool $ws = false): array|stdClass
    {
        $r_modifica =  parent::modifica(header: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_modifica, header: $header,ws:$ws);
        }

        $producto = (new cat_sat_producto($this->link))->get_producto($this->row_upd->cat_sat_producto_id);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener $producto',data:  $producto);
        }


        $identificador = "cat_sat_unidad_id";
        $propiedades = array("id_selected" => $this->row_upd->cat_sat_unidad_id);
        $this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);

        $identificador = "cat_sat_obj_imp_id";
        $propiedades = array("id_selected" => $this->row_upd->cat_sat_obj_imp_id);
        $this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);

        $identificador = "com_tipo_producto_id";
        $propiedades = array("id_selected" => $this->row_upd->com_tipo_producto_id);
        $this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);

        $identificador = "cat_sat_conf_imps_id";
        $propiedades = array("id_selected" => $this->row_upd->cat_sat_conf_imps_id);
        $this->asignar_propiedad(identificador:$identificador, propiedades: $propiedades);

        $inputs = $this->genera_inputs(keys_selects:  $this->keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar inputs',data:  $inputs);
        }

        $this->row_upd->cat_sat_producto = $this->row_upd->codigo_sat;


        $tmp_transaccion = (new com_producto(link: $this->link))->ejecuta_upd_tmp(com_producto_id: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al actualizar',data:  $tmp_transaccion, header: $header,ws:  $ws);
        }

        $disabled = true;
        //if($this->row_upd->cat_sat_producto !== $this->registro['cat_sat_producto_codigo']){
        //    $disabled = false;
        //}
        $cat_sat_producto = (new com_producto_html(html: $this->html_base))->input_text_required(cols: 6,
            disabled: $disabled, name: 'codigo_sat',place_holder:  'Codigo SAT',row_upd:  $this->row_upd,
            value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $cat_sat_producto, header: $header,ws:  $ws);
        }

        $this->inputs->cat_sat_producto = $cat_sat_producto;

        $link_com_producto_modifica_bd = $this->obj_link->link_con_id(accion: 'modifica_bd',link:  $this->link,
            registro_id:  $this->registro_id,seccion: $this->seccion);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener link_com_producto_modifica_bd',
                data:  $link_com_producto_modifica_bd, header: $header,ws:  $ws);
        }

        $this->link_com_producto_modifica_bd = $link_com_producto_modifica_bd;



        return $r_modifica;
    }


}
