<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\comercial\controllers;

use gamboamartin\comercial\models\com_tmp_cte_dp;
use gamboamartin\errores\errores;
use gamboamartin\template\html;
use html\com_cliente_html;
use html\com_tmp_cte_dp_html;
use PDO;
use stdClass;
use Throwable;

class controlador_com_tmp_cte_dp extends _base_sin_cod {

    public array|stdClass $keys_selects = array();

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){

        $modelo = new com_tmp_cte_dp(link: $link);
        $html_ = new com_tmp_cte_dp_html(html: $html);

        parent::__construct(html_: $html_,link:  $link,modelo:  $modelo, paths_conf: $paths_conf);



    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = parent::alta(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta,header:  $header,ws:  $ws);
        }

        $com_cliente_id = (new com_cliente_html(html: $this->html_base))->select_com_cliente_id(cols: 12,
            con_registros: true,id_selected: -1,link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $com_cliente_id,header:  $header,ws:  $ws);
        }

        $this->inputs->com_cliente_id  = $com_cliente_id;

        $dp_pais = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_pais(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_pais  = $dp_pais;

        $dp_estado = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_estado(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_estado  = $dp_estado;

        $dp_municipio = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_municipio(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_municipio  = $dp_municipio;

        $dp_cp = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_cp(cols: 12,row_upd: $this->row_upd,value_vacio: false, required: true);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_cp,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_cp  = $dp_cp;

        $dp_colonia = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_colonia(cols: 12,
            row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_colonia,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_colonia  = $dp_colonia;

        $dp_calle = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_calle(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_calle  = $dp_calle;


        return $r_alta;

    }


    public function init_datatable(): stdClass
    {
        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['com_tmp_cte_dp_id']['titulo'] = 'Id';
        $datatables->columns['com_tmp_cte_dp_descripcion']['titulo'] = 'Descripcion';

        $datatables->filtro = array();
        $datatables->filtro[] = 'com_tmp_cte_dp.id';
        $datatables->filtro[] = 'com_tmp_cte_dp.descripcion';

        return $datatables;
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $r_modifica = parent::modifica($header, $ws, $keys_selects); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_modifica,header:  $header,ws:  $ws);
        }
        $com_cliente_id = (new com_cliente_html(html: $this->html_base))->select_com_cliente_id(cols: 12,
            con_registros: true,id_selected: $this->row_upd->com_cliente_id,link: $this->link);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $com_cliente_id,header:  $header,ws:  $ws);
        }

        $this->inputs->com_cliente_id  = $com_cliente_id;

        $dp_pais = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_pais(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_pais  = $dp_pais;

        $dp_estado = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_estado(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_estado  = $dp_estado;

        $dp_municipio = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_municipio(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_municipio  = $dp_municipio;

        $dp_cp = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_cp(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_cp,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_cp  = $dp_cp;

        $dp_colonia = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_colonia(cols: 12,
            row_upd: $this->row_upd,value_vacio: false, required: true);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_colonia  = $dp_colonia;

        $dp_calle = (new com_tmp_cte_dp_html(html: $this->html_base))->input_dp_calle(cols: 12,row_upd: $this->row_upd,value_vacio: false);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input',data:  $dp_pais,header:  $header,ws:  $ws);
        }

        $this->inputs->dp_calle  = $dp_calle;


        return $r_modifica;
    }

    public function regenera(bool $header, bool $ws = false){

        $regenera = (new com_tmp_cte_dp(link: $this->link))->regenera(com_tmp_cte_dp_id: $this->registro_id);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al eliminar temporal',data:  $regenera,header:  $header,ws:  $ws);
        }

        if($header){

            $this->retorno_base(registro_id:-1, result: $regenera, siguiente_view: 'lista',
                ws:  $ws,seccion_retorno: $this->tabla);
        }
        if($ws){
            header('Content-Type: application/json');
            try {
                echo json_encode($regenera, JSON_THROW_ON_ERROR);
            }
            catch (Throwable $e){
                $error = (new errores())->error(mensaje: 'Error al maquetar JSON' , data: $e);
                print_r($error);
            }
            exit;
        }

        return $regenera;



    }


}
