<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */

namespace gamboamartin\comercial\controllers;

use base\controller\init;
use gamboamartin\comercial\models\com_direccion;
use gamboamartin\comercial\models\com_direccion_prospecto;
use gamboamartin\comercial\models\com_prospecto;
use gamboamartin\comercial\models\com_prospecto_etapa;
use gamboamartin\errores\errores;
use gamboamartin\proceso\html\pr_etapa_proceso_html;
use gamboamartin\system\actions;
use gamboamartin\template\html;
use html\com_agente_html;
use html\com_prospecto_html;
use html\com_tipo_prospecto_html;
use PDO;
use stdClass;
use Throwable;

class controlador_com_prospecto extends _base_sin_cod
{

    public array|stdClass $keys_selects = array();
    public string $link_alta_etapa = '';
    public string $link_alta_direccion = '';
    public string $link_alta_relacion = '';
    public array $etapas = array();

    public function __construct(PDO      $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass())
    {
        $modelo = new com_prospecto(link: $link);
        $html_ = new com_prospecto_html(html: $html);
        parent::__construct(html_: $html_, link: $link, modelo: $modelo, paths_conf: $paths_conf);

        $init_links = $this->init_links();
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al inicializar links', data: $init_links);
            print_r($error);
            die('Error');
        }

    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta = $this->init_alta();
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al inicializar alta', data: $r_alta, header: $header, ws: $ws);
        }

        $keys_selects = $this->init_selects_inputs();
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al inicializar selects', data: $keys_selects, header: $header,
                ws: $ws);
        }

        $inputs = $this->inputs(keys_selects: $keys_selects);
        if (errores::$error) {
            return $this->retorno_error(
                mensaje: 'Error al obtener inputs', data: $inputs, header: $header, ws: $ws);
        }

        return $r_alta;
    }

    protected function campos_view(array $inputs = array()): array
    {
        $keys = new stdClass();
        $keys->inputs = array('codigo', 'descripcion', 'nombre', 'apellido_paterno', 'apellido_materno', 'telefono',
            'correo', 'razon_social', 'texto_exterior', 'texto_interior');
        $keys->selects = array();

        $init_data = array();
        $init_data['com_tipo_prospecto'] = "gamboamartin\\comercial";
        $init_data['com_agente'] = "gamboamartin\\comercial";
        $init_data['dp_pais'] = "gamboamartin\\direccion_postal";
        $init_data['dp_estado'] = "gamboamartin\\direccion_postal";
        $init_data['dp_municipio'] = "gamboamartin\\direccion_postal";
        $init_data['dp_cp'] = "gamboamartin\\direccion_postal";
        $init_data['dp_colonia_postal'] = "gamboamartin\\direccion_postal";
        $init_data['dp_calle_pertenece'] = "gamboamartin\\direccion_postal";
        $init_data['com_tipo_direccion'] = "gamboamartin\\comercial";
        $init_data['com_direccion'] = "gamboamartin\\comercial";

        $campos_view = $this->campos_view_base(init_data: $init_data, keys: $keys);
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al inicializar campo view', data: $campos_view);
        }

        return $campos_view;
    }

    public function convierte_en_cliente(bool $header, bool $ws = false): array|stdClass
    {

        $convierte_en_cliente = (new com_prospecto(link: $this->link))->convierte_en_cliente(com_prospecto_id: $this->registro_id);
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al convertir en cliente', data: $convierte_en_cliente, header: $header, ws: $ws);
        }
        if ($header) {

            $this->retorno_base(registro_id: -1, result: $convierte_en_cliente, siguiente_view: 'lista',
                ws: $ws, seccion_retorno: $this->seccion, valida_permiso: true);
        }
        if ($ws) {
            header('Content-Type: application/json');
            try {
                echo json_encode($convierte_en_cliente, JSON_THROW_ON_ERROR);
            } catch (Throwable $e) {
                $error = (new errores())->error(mensaje: 'Error al maquetar JSON', data: $e);
                print_r($error);
            }
            exit;
        }

        return $convierte_en_cliente;
    }

    public function etapa(bool $header, bool $ws = false): array|stdClass
    {
        $keys_selects = array();
        $template = parent::modifica(header: false, keys_selects: $keys_selects); // TODO: Change the autogenerated stub
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al generar template', data: $template, header: $header, ws: $ws);
        }


        $filtro = array();
        $filtro['pr_proceso.descripcion'] = 'PROSPECCION';
        $columns_ds[] = 'pr_etapa_descripcion';

        $pr_etapa_proceso_id = (new pr_etapa_proceso_html(html: $this->html_base))->select_pr_etapa_proceso_id(
            cols: 12, con_registros: true, id_selected: -1, link: $this->link, columns_ds: $columns_ds,
            filtro: $filtro, label: 'Etapa');
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al obtener selector de etapa', data: $pr_etapa_proceso_id, header: $header, ws: $ws);
        }

        $this->inputs->pr_etapa_proceso_id = $pr_etapa_proceso_id;
        $hoy = date('Y-m-d');
        $fecha = $this->html->input_fecha(cols: 12, row_upd: new stdClass(), value_vacio: false, value: $hoy);
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al generar input fecha', data: $fecha, header: $header, ws: $ws);
        }

        $this->inputs->fecha = $fecha;

        $link_alta_etapa = $this->obj_link->link_con_id(
            accion: 'etapa_bd', link: $this->link, registro_id: $this->registro_id, seccion: $this->tabla);
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al generar link', data: $link_alta_etapa, header: $header, ws: $ws);
        }


        $this->link_alta_etapa = $link_alta_etapa;

        $etapas = (new com_prospecto(link: $this->link))->etapas(com_prospecto_id: $this->registro_id);
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al obtener etapas', data: $etapas, header: $header, ws: $ws);
        }

        $this->etapas = $etapas;


        return $template;
    }

    public function etapa_bd(bool $header, bool $ws = false): array|stdClass
    {

        $this->link->beginTransaction();


        $com_prospecto_etapa_ins['com_prospecto_id'] = $this->registro_id;
        $com_prospecto_etapa_ins['pr_etapa_proceso_id'] = $_POST['pr_etapa_proceso_id'];
        $com_prospecto_etapa_ins['fecha'] = $_POST['fecha'];

        $r_alta_com_prospecto_etapa = (new com_prospecto_etapa(link: $this->link))->alta_registro(registro: $com_prospecto_etapa_ins);
        if (errores::$error) {
            $this->link->rollBack();
            $this->retorno_error(mensaje: 'Error al insertar com_prospecto_etapa', data: $r_alta_com_prospecto_etapa, header: $header, ws: $ws);
        }
        $this->link->commit();

        if ($header) {

            $this->retorno_base(registro_id: $this->registro_id, result: $r_alta_com_prospecto_etapa, siguiente_view: 'etapa',
                ws: $ws, seccion_retorno: $this->seccion, valida_permiso: true);
        }
        if ($ws) {
            header('Content-Type: application/json');
            try {
                echo json_encode($r_alta_com_prospecto_etapa, JSON_THROW_ON_ERROR);
            } catch (Throwable $e) {
                $error = (new errores())->error(mensaje: 'Error al maquetar JSON', data: $e);
                print_r($error);
            }
            exit;
        }


        return $r_alta_com_prospecto_etapa;
    }

    public function init_datatable(): stdClass
    {
        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['com_prospecto_id']['titulo'] = 'Id';
        $datatables->columns['com_prospecto_descripcion']['titulo'] = 'Prospecto';


        $datatables->filtro = array();
        $datatables->filtro[] = 'com_prospecto.id';
        $datatables->filtro[] = 'com_prospecto.descripcion';

        return $datatables;
    }

    private function init_selects(array $keys_selects, string $key, string $label, int $id_selected = -1, int $cols = 6,
                                  bool  $con_registros = true, array $filtro = array()): array
    {
        $keys_selects = $this->key_select(cols: $cols, con_registros: $con_registros, filtro: $filtro, key: $key,
            keys_selects: $keys_selects, id_selected: $id_selected, label: $label);
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        return $keys_selects;
    }

    public function init_selects_inputs(): array
    {
        $keys_selects = $this->init_selects(keys_selects: array(), key: "com_tipo_prospecto_id", label: "Tipo Propecto");
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "com_agente_id", label: "Agente");
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "com_tipo_direccion_id", label: "Tipo Dirección", cols: 12);
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_pais_id", label: "País");
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_estado_id", label: "Estado",
            con_registros: false);
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_municipio_id", label: "Municipio",
            con_registros: false);
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_cp_id", label: "CP",
            con_registros: false);
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_colonia_postal_id", label: "Colonia",
            con_registros: false);
        $keys_selects = $this->init_selects(keys_selects: $keys_selects, key: "dp_calle_pertenece_id", label: "Calle",
            con_registros: false);
        return $this->init_selects(keys_selects: $keys_selects, key: "com_direccion_id", label: "Dirección", cols: 12);

    }

    protected function init_links(): array|string
    {
        $links = $this->obj_link->genera_links(controler: $this);
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al generar links', data: $links);
            print_r($error);
            exit;
        }

        $link = $this->obj_link->get_link(seccion: "com_prospecto", accion: "alta_direccion");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link alta_direccion', data: $link);
            print_r($error);
            exit;
        }
        $this->link_alta_direccion = $link;

        $link = $this->obj_link->get_link(seccion: "com_prospecto", accion: "alta_relacion");
        if (errores::$error) {
            $error = $this->errores->error(mensaje: 'Error al recuperar link alta_direccion', data: $link);
            print_r($error);
            exit;
        }
        $this->link_alta_relacion = $link;

        return $link;
    }


    protected function key_selects_txt(array $keys_selects): array
    {
        $keys_selects = (new init())->key_select_txt(cols: 4, key: 'codigo',
            keys_selects: $keys_selects, place_holder: 'Cod');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 8, key: 'descripcion',
            keys_selects: $keys_selects, place_holder: 'Tipo Agente');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'nombre',
            keys_selects: $keys_selects, place_holder: 'Nombre');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }
        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'apellido_paterno',
            keys_selects: $keys_selects, place_holder: 'AP');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }
        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'apellido_materno',
            keys_selects: $keys_selects, place_holder: 'AM');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }
        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'telefono',
            keys_selects: $keys_selects, place_holder: 'Tel');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }
        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'correo',
            keys_selects: $keys_selects, place_holder: 'Correo');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }
        $keys_selects = (new init())->key_select_txt(cols: 6, key: 'razon_social',
            keys_selects: $keys_selects, place_holder: 'Razon Social');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6, key: 'texto_exterior',
            keys_selects: $keys_selects, place_holder: 'Exterior');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6, key: 'texto_interior',
            keys_selects: $keys_selects, place_holder: 'Interior');
        if (errores::$error) {
            return $this->errores->error(mensaje: 'Error al maquetar key_selects', data: $keys_selects);
        }

        return $keys_selects;
    }

    public function modifica(bool $header, bool $ws = false, array $keys_selects = array()): array|stdClass
    {
        $template = parent::modifica(header: false, keys_selects: $keys_selects); // TODO: Change the autogenerated stub
        if (errores::$error) {
            $this->retorno_error(mensaje: 'Error al generar template', data: $template, header: $header, ws: $ws);
        }

        $keys_selects = $this->init_selects_inputs();
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al inicializar selects', data: $keys_selects, header: $header,
                ws: $ws);
        }

        $keys_selects['com_tipo_prospecto_id']->id_selected = $this->row_upd->com_tipo_prospecto_id;
        $keys_selects['com_agente_id']->id_selected = $this->row_upd->com_agente_id;

        $base = $this->base_upd(keys_selects: $keys_selects, params: array(), params_ajustados: array());
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al integrar base', data: $base, header: $header, ws: $ws);
        }

        $columns["com_direccion_id"]["titulo"] = "Id";
        $columns["com_tipo_direccion_descripcion"]["titulo"] = "Tipo";
        $columns["dp_calle_pertenece_descripcion"]["titulo"] = "Calle";
        $columns["com_direccion_texto_exterior"]["titulo"] = "Exterior";
        $columns["com_direccion_texto_interior"]["titulo"] = "Interior";

        $filtro = array("com_direccion.id","com_tipo_direccion.descripcion", "com_direccion.texto_exterior", "com_direccion.texto_interior");

        $datatables = $this->datatable_init(columns: $columns, filtro: $filtro, identificador: "#com_direccion",
            data: array(), in: array());
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al inicializar datatable', data: $datatables,
                header: $header, ws: $ws);
        }

        $columns = array();
        $columns["com_direccion_prospecto_id"]["titulo"] = "Id";
        $columns["com_direccion_descripcion"]["titulo"] = "Dirección";
        $columns["com_prospecto_descripcion"]["titulo"] = "Prospecto";

        $filtro = array("com_direccion.id","com_direccion.descripcion","com_prospecto.descripcion");

        $data = array();
        $data["com_prospecto.id"] = $this->registro_id;

        $datatables = $this->datatable_init(columns: $columns, filtro: $filtro, identificador: "#com_direccion_prospecto",
            data: array(), in: array());
        if (errores::$error) {
            return $this->retorno_error(mensaje: 'Error al inicializar datatable', data: $datatables,
                header: $header, ws: $ws);
        }


        return $template;
    }

    public function alta_direccion(bool $header, bool $ws = false): array|stdClass
    {
        $this->link->beginTransaction();

        $siguiente_view = (new actions())->init_alta_bd();
        if (errores::$error) {
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al obtener siguiente view', data: $siguiente_view,
                header: $header, ws: $ws);
        }

        if (isset($_POST['btn_action_next'])) {
            unset($_POST['btn_action_next']);
        }

        $alta = (new com_direccion($this->link))->alta_registro(registro: $_POST);
        if (errores::$error) {
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al dar de alta direccion', data: $alta,
                header: $header, ws: $ws);
        }

        $this->link->commit();

        if ($header) {
            $this->retorno_base(registro_id: $this->registro_id, result: $alta,
                siguiente_view: "modifica", ws: $ws);
        }
        if ($ws) {
            header('Content-Type: application/json');
            echo json_encode($alta, JSON_THROW_ON_ERROR);
            exit;
        }
        $alta->siguiente_view = "modifica";
        $alta->registro_id = $this->registro_id;

        return $alta;
    }

    public function alta_relacion(bool $header, bool $ws = false): array|stdClass
    {
        $this->link->beginTransaction();

        $siguiente_view = (new actions())->init_alta_bd();
        if (errores::$error) {
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al obtener siguiente view', data: $siguiente_view,
                header: $header, ws: $ws);
        }

        if (isset($_POST['btn_action_next'])) {
            unset($_POST['btn_action_next']);
        }

        $registros = array();
        $registros['com_prospecto_id'] = $this->registro_id;
        $registros['com_direccion_id'] = $_POST['com_direccion_id'];
        $alta = (new com_direccion_prospecto($this->link))->alta_registro(registro: $registros);
        if (errores::$error) {
            $this->link->rollBack();
            return $this->retorno_error(mensaje: 'Error al dar de alta direccion prospecto', data: $alta,
                header: $header, ws: $ws);
        }

        $this->link->commit();

        if ($header) {
            $this->retorno_base(registro_id: $this->registro_id, result: $alta,
                siguiente_view: "modifica", ws: $ws);
        }
        if ($ws) {
            header('Content-Type: application/json');
            echo json_encode($alta, JSON_THROW_ON_ERROR);
            exit;
        }
        $alta->siguiente_view = "modifica";
        $alta->registro_id = $this->registro_id;

        return $alta;
    }
}
